/* AUTO-GENERATED by scripts/generate-placeholders.mjs — do not edit by hand.
 *
 * imageManifest maps every image slot to the asset currently shown on the
 * site:
 *   - a real photograph when one exists at public/images/<slot.file>
 *   - otherwise the branded placeholder SVG for that slot.
 *
 * imageRegistry carries each slot's display metadata (aspect ratio, alt
 * text, gallery category, caption).
 *
 * To publish real photos, drop files into public/images/ using the names
 * listed in scripts/image-slots.mjs, then run "npm run images" or rebuild.
 */

export interface GeneratedSlot {
  id: ImageSlotId;
  file: string;
  aspect: "wide" | "landscape" | "portrait";
  variant: "dark" | "light";
  quiet?: boolean;
  label: string;
  alt: string;
  category: "weddings" | "events" | "food" | "kids" | "venue";
  caption: string;
}

export type ImageSlotId =
  | "hero-home"
  | "hero-weddings"
  | "hero-venue"
  | "hero-services"
  | "hero-gallery"
  | "hero-about"
  | "hero-contact"
  | "hero-kids"
  | "venue-hall"
  | "venue-garden"
  | "venue-rooftop"
  | "venue-detail"
  | "wedding-ceremony"
  | "wedding-reception"
  | "wedding-decor"
  | "event-birthday"
  | "event-meeting"
  | "service-decoration"
  | "service-catering"
  | "service-bargrill"
  | "service-coffee"
  | "service-kids"
  | "kids-play"
  | "kids-party"
  | "family-day"
  | "about-moments";

export const imageManifest: Record<
  ImageSlotId,
  { src: string; placeholder: boolean; generated: boolean }
> = {
  "hero-home": {
    "src": "/images/concept/hero-home.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-weddings": {
    "src": "/images/concept/hero-weddings.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-venue": {
    "src": "/images/concept/hero-venue.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-services": {
    "src": "/images/concept/hero-services.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-gallery": {
    "src": "/images/concept/hero-gallery.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-about": {
    "src": "/images/concept/hero-about.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-contact": {
    "src": "/images/concept/hero-contact.jpg",
    "placeholder": false,
    "generated": true
  },
  "hero-kids": {
    "src": "/images/concept/hero-kids.jpg",
    "placeholder": false,
    "generated": true
  },
  "venue-hall": {
    "src": "/images/concept/venue-hall.jpg",
    "placeholder": false,
    "generated": true
  },
  "venue-garden": {
    "src": "/images/concept/venue-garden.jpg",
    "placeholder": false,
    "generated": true
  },
  "venue-rooftop": {
    "src": "/images/placeholders/venue-rooftop.svg",
    "placeholder": true,
    "generated": false
  },
  "venue-detail": {
    "src": "/images/placeholders/venue-detail.svg",
    "placeholder": true,
    "generated": false
  },
  "wedding-ceremony": {
    "src": "/images/placeholders/wedding-ceremony.svg",
    "placeholder": true,
    "generated": false
  },
  "wedding-reception": {
    "src": "/images/placeholders/wedding-reception.svg",
    "placeholder": true,
    "generated": false
  },
  "wedding-decor": {
    "src": "/images/placeholders/wedding-decor.svg",
    "placeholder": true,
    "generated": false
  },
  "event-birthday": {
    "src": "/images/placeholders/event-birthday.svg",
    "placeholder": true,
    "generated": false
  },
  "event-meeting": {
    "src": "/images/placeholders/event-meeting.svg",
    "placeholder": true,
    "generated": false
  },
  "service-decoration": {
    "src": "/images/placeholders/service-decoration.svg",
    "placeholder": true,
    "generated": false
  },
  "service-catering": {
    "src": "/images/placeholders/service-catering.svg",
    "placeholder": true,
    "generated": false
  },
  "service-bargrill": {
    "src": "/images/placeholders/service-bargrill.svg",
    "placeholder": true,
    "generated": false
  },
  "service-coffee": {
    "src": "/images/placeholders/service-coffee.svg",
    "placeholder": true,
    "generated": false
  },
  "service-kids": {
    "src": "/images/placeholders/service-kids.svg",
    "placeholder": true,
    "generated": false
  },
  "kids-play": {
    "src": "/images/placeholders/kids-play.svg",
    "placeholder": true,
    "generated": false
  },
  "kids-party": {
    "src": "/images/placeholders/kids-party.svg",
    "placeholder": true,
    "generated": false
  },
  "family-day": {
    "src": "/images/placeholders/family-day.svg",
    "placeholder": true,
    "generated": false
  },
  "about-moments": {
    "src": "/images/placeholders/about-moments.svg",
    "placeholder": true,
    "generated": false
  }
};

export const imageRegistry: GeneratedSlot[] = [
  {
    "id": "hero-home",
    "file": "hero/home.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "The Venue at a Glance",
    "alt": "Wide view of INZOZI PARK — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-weddings",
    "file": "hero/weddings.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Weddings at INZOZI PARK",
    "alt": "Wedding scene at INZOZI PARK — photo to be provided by the venue",
    "category": "weddings",
    "caption": ""
  },
  {
    "id": "hero-venue",
    "file": "hero/venue.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Venue & Events",
    "alt": "INZOZI PARK event spaces — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-services",
    "file": "hero/services.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Our Services",
    "alt": "INZOZI PARK services — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-gallery",
    "file": "hero/gallery.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "The INZOZI PARK Collection",
    "alt": "INZOZI PARK photo collection — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-about",
    "file": "hero/about.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Our Story",
    "alt": "INZOZI PARK story — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-contact",
    "file": "hero/contact.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Visit INZOZI PARK",
    "alt": "Arrival at INZOZI PARK — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "hero-kids",
    "file": "hero/kids.jpg",
    "aspect": "wide",
    "variant": "dark",
    "quiet": true,
    "label": "Kids & Family",
    "alt": "Children playing at INZOZI KIDS PARK — photo to be provided by the venue",
    "category": "kids",
    "caption": ""
  },
  {
    "id": "venue-hall",
    "file": "venue/hall.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Main Event Hall",
    "alt": "INZOZI PARK main event hall — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "venue-garden",
    "file": "venue/garden.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Garden & Grounds",
    "alt": "INZOZI PARK garden — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "venue-rooftop",
    "file": "venue/rooftop.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Rooftop Bar & Lounge",
    "alt": "Rooftop bar at INZOZI PARK — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "venue-detail",
    "file": "venue/detail.jpg",
    "aspect": "portrait",
    "variant": "light",
    "label": "Venue Details",
    "alt": "Detail at INZOZI PARK — photo to be provided by the venue",
    "category": "venue",
    "caption": ""
  },
  {
    "id": "wedding-ceremony",
    "file": "weddings/ceremony.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Ceremony Setup",
    "alt": "Wedding ceremony setup at INZOZI PARK — photo to be provided by the venue",
    "category": "weddings",
    "caption": ""
  },
  {
    "id": "wedding-reception",
    "file": "weddings/reception.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Reception & Décor",
    "alt": "Wedding reception at INZOZI PARK — photo to be provided by the venue",
    "category": "weddings",
    "caption": ""
  },
  {
    "id": "wedding-decor",
    "file": "weddings/decor.jpg",
    "aspect": "portrait",
    "variant": "light",
    "label": "Decoration Details",
    "alt": "Wedding decoration at INZOZI PARK — photo to be provided by the venue",
    "category": "weddings",
    "caption": ""
  },
  {
    "id": "event-birthday",
    "file": "events/birthday.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Birthday Celebrations",
    "alt": "Birthday celebration at INZOZI PARK — photo to be provided by the venue",
    "category": "events",
    "caption": ""
  },
  {
    "id": "event-meeting",
    "file": "events/meeting.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Meetings & Gatherings",
    "alt": "Meeting setup at INZOZI PARK — photo to be provided by the venue",
    "category": "events",
    "caption": ""
  },
  {
    "id": "service-decoration",
    "file": "services/decoration.jpg",
    "aspect": "portrait",
    "variant": "light",
    "label": "Decoration",
    "alt": "Event decoration by INZOZI PARK — photo to be provided by the venue",
    "category": "weddings",
    "caption": ""
  },
  {
    "id": "service-catering",
    "file": "services/catering.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Catering",
    "alt": "Catering at INZOZI PARK — photo to be provided by the venue",
    "category": "food",
    "caption": ""
  },
  {
    "id": "service-bargrill",
    "file": "services/bar-grill.jpg",
    "aspect": "portrait",
    "variant": "light",
    "label": "Bar & Grill",
    "alt": "Bar & Grill at INZOZI PARK — photo to be provided by the venue",
    "category": "food",
    "caption": ""
  },
  {
    "id": "service-coffee",
    "file": "services/coffee.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Coffee & Refreshments",
    "alt": "Coffee at INZOZI PARK — photo to be provided by the venue",
    "category": "food",
    "caption": ""
  },
  {
    "id": "service-kids",
    "file": "services/kids.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Kids Park",
    "alt": "INZOZI KIDS PARK — photo to be provided by the venue",
    "category": "kids",
    "caption": ""
  },
  {
    "id": "kids-play",
    "file": "kids/play.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Play Experiences",
    "alt": "Play activities at INZOZI KIDS PARK — photo to be provided by the venue",
    "category": "kids",
    "caption": ""
  },
  {
    "id": "kids-party",
    "file": "kids/party.jpg",
    "aspect": "portrait",
    "variant": "light",
    "label": "Kids' Parties",
    "alt": "Kids' party at INZOZI PARK — photo to be provided by the venue",
    "category": "kids",
    "caption": ""
  },
  {
    "id": "family-day",
    "file": "kids/family-day.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Family Days",
    "alt": "Family day at INZOZI PARK — photo to be provided by the venue",
    "category": "kids",
    "caption": ""
  },
  {
    "id": "about-moments",
    "file": "about/moments.jpg",
    "aspect": "landscape",
    "variant": "light",
    "label": "Moments at INZOZI PARK",
    "alt": "Moments at INZOZI PARK — photo to be provided by the venue",
    "category": "events",
    "caption": ""
  }
];

export const IMAGE_SLOT_COUNT = 26;
export const PLACEHOLDER_COUNT = 16;
